import os
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
WINDOW_TITLE = "test"
BOOL_ISFULLSCREEN = False
BACKGROUND_COLOR = (34,139,34)
MUSIC_VOLUME = 0.5
GITHUB_REPO_PAGE = "https://github.com/Silentfeeel/towerdefence"